- name: Install Maven init script
  copy: src=apache-maven-3.5.2-bin.tar.gz dest=/tmp/apache-maven-3.5.2-bin.tar.gz mode=0755
- name: Installing package on target server jre
  yum:
    name: "tar"
    state: present
  become: true
  tags: installing_package
- name: Extract archive
  command: chdir=/tmp /usr/bin/tar xvf /tmp/apache-maven-3.5.2-bin.tar.gz -C /tmp/ creates=/tmp/apache-maven-3.5.2
  mode: 0777

- name: Creating entries for M2_HOME and PATH in profile file
  lineinfile:
    dest: "{{ profile_path }}"
    line: "{{ item }}"
#    state: present
  with_items:
    - "{{ env_var_entries }}"
  become: true
  tags: adding_env_entries

- name: Creating entries for M2_HOME and PATH in profile file
  lineinfile:
    dest: "{{ profile_path }}"
    line: "{{ item }}"
#    state: present
  with_items:
    - "{{ env_var_entries1 }}"
  become: true
  tags: adding_env_entries1

- name: refreshing source file
  shell: source /etc/profile

- name: Creating entries bashrc file
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
#    state: present
  with_items:
    - "{{ env_var_entries }}"
  become: true
  tags: adding_env_entries

- name: Creating entries in bashrc file
  lineinfile:
    path: "~/.bashrc"
    line: "{{ item }}"
#    state: present
  with_items:
    - "{{ env_var_entries1 }}"
  become: true
  tags: adding_env_entries1

- name: refreshing source file
  shell:  source ~/.bashrc

